export const LOYALTY_PROMOTION_PREFIX = "LOYALTY"
export const LOYALTY_EARN_SPEND = 10_000
export const LOYALTY_REDEMPTION_POINTS = 100
export const LOYALTY_REDEMPTION_VALUE = 10_000
export const FIRST_PURCHASE_PROMOTION_CODE = "FIRST_PURCHASE"
