export const FIRST_PURCHASE_PROMOTION_CODE = "FIRST_PURCHASE";
export const CUSTOMER_ID_PROMOTION_RULE_ATTRIBUTE = "customer_id";
export const LOYALTY_EARN_VND_PER_POINT = 10_000;
export const LOYALTY_REDEEM_POINTS_PER_BLOCK = 100;
export const LOYALTY_REDEEM_VND_PER_BLOCK = 20_000;
