export const FIRST_PURCHASE_PROMOTION_CODE = "FIRST_PURCHASE";
export const CUSTOMER_ID_PROMOTION_RULE_ATTRIBUTE = "customer_id";
export const LOYALTY_EARN_VND_PER_POINT = 10_000;
export const LOYALTY_REDEEM_VND_PER_POINT = 500;

export const VIP_TIER_NAME = "VIP";
export const VIP_BUNDLE_PROMOTION_CODE = "VIP_BUNDLE_15";
export const RACKET_SUMMER_GET_SOCK_PROMOTION_CODE = "RACKET_SUMMER_GET_SOCK";
export const FLASH_PROMOTION_CODE_PREFIX = "FLASH20-";
export const FLASH_CAMPAIGN_IDENTIFIER = "FLASH20_DAILY";
export const FLASH_PROMOTION_MAX_DISCOUNT = 300_000;
export const FLASH_CAMPAIGN_BUDGET = 20_000_000;
export const FLASH_CUSTOMER_USAGE_LIMIT = 2;
